- name: Demo on variable
  hosts: all
  vars:
    URL: file.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        #        msg: URL = {{ URL }}         # This is not a variable
        msg: "{{ URL }} is the URL"  # This is a Variable

- name: Demo on file variable
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}



- name: Task level variable
  hosts: all
  tasks:
    -name: Print URL
    ansible.builtin.debug:
      msg: URL = {{URL}}
      vars:
        URL: task.example.com