- name: Demo on Variable
  hosts: all
  vars:
    URL: Play.example.com
  tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL = {{ URL }}
          msg: "{{ URL }}} is the URL"